### ISSUE TITLE
Open other view controllers?

### ISSUE THREAD

**Issue by haleyngonadi** [WXGBridgeQ/WXGSlideMenuDemo#1]
This is amazing! Such a great control. How do I open other viewcontrollers in the container? :)

**Comment by WXGBridgeQ** [comment]
Thanks for your encourage.
For your question, if you use storyboard, you just need to drag a container view, the storyboard will auto create a new view controller for you, if you use code manually, you need to create the view controller, add it to the super view controller and add its view to the super view controller's view.
It's not so difficult, you just need to understand the hierarchical relationship of view controllers and views.

**Comment by haleyngonadi** [comment]
I'm a bit confused. How do I link up the new views to the controller's menu?

**Comment by WXGBridgeQ** [comment]
Actually it's one main controller which has two child controllers (a menu controller and a content controller), you can handle the child controller's event in the main controller, using block, delegate or other ways.
I hope this has answered your question.

**Comment by haleyngonadi** [comment]
Made a new view controller;

   WXGMenuViewController *menuViewController = [[WXGMenuViewController alloc] init];
    self.menuViewController = menuViewController;
    UINavigationController *menuNavigationController = [[UINavigationController alloc] initWithRootViewController:menuViewController];
    [self addChildViewController:menuNavigationController];

```
WXGDetailViewController *detailViewController = [[WXGDetailViewController alloc] init];
detailViewController.title = @"Home";
self.detailViewController = detailViewController;
UINavigationController *detailNavigationController = [[UINavigationController alloc] initWithRootViewController:detailViewController];
[self addChildViewController:detailNavigationController];
```

```
    ShowViewController *showViewController = [[ShowViewController alloc] init];
    self.showViewController = showViewController;
    UINavigationController *showNavigationController = [[UINavigationController alloc] initWithRootViewController:showViewController];
    [self addChildViewController:showNavigationController];

```

but not working :/
